[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Ken Erwin <ken.erwin@traderev.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
